### ISSUE TITLE
Dynamic modification to sophia.conf

### ISSUE THREAD

**Issue by Kays** [Kays/sophia#16]
Enable commands to dynamically change sophia.conf values. With the save feature, this enables easy moderation.

**Comment by myano** [comment]
I can understand ticket #15, so owner's and/or admins can change settings. However, for a security purpose should arbitrary commands be allowed to make configuration changes?

**Comment by Kays** [comment]
Owners should be able to change the bot's nick, username, trigger, assign owners/admins, etc and save a configuration file from sophia. It makes sense. I don't want to edit a file and restart sophia every time I want to add an admin or modify one small setting.
