### ISSUE TITLE
MODULE: common.help

### ISSUE THREAD

**Issue by myano** [Kays/sophia#21]
Need a help command or a command to send a user a private message of all available commands.

**Comment by Kays** [comment]
How would this work? It'll have to privmsg them commands, syntax and perhaps a short description. And since sophia is a bot and not services, it can't do that as fast as ChanServ. So it'll be throttled far too much.

**Comment by myano** [comment]
Couldn't we create an array of all the commands loaded and have another command just display all them in one line via PM?

**Comment by Kays** [comment]
In what format? Also, each buffer has a char limit. So that may not work too well.

Something like:
.dict <word>, .wiki <text>, etc?

I suppose.... Not sure how useful this would be.

**Comment by myano** [comment]
We could list them like that. Also we could set up a module to query the information we put in at the top of the modules on what they are used for.

**Comment by Kays** [comment]
0dc6687317648298851b899c80e54c8d00350db6

Closed!
