### ISSUE TITLE
Extend common.time capabilities

### ISSUE THREAD

**Issue by Kays** [Kays/sophia#34]
!time edt + 4 should be valid.

**Comment by Kays** [comment]
Rather than enabling "!time edt + 4" we can just do:

Google with "time &lt;location&gt;" should work with this. It will actually make it more useful. So something like:
Kays:> !time Chicago
sophia:> 12:35am Tuesday (CDT) - Time in Chicago, IL

**Comment by myano** [comment]
that won't work for all time zone codes we already have programmed in.
