### ISSUE TITLE
Score / Point System

### ISSUE THREAD

**Issue by myano** [Kays/sophia#50]
This would be similar to jenni's score / point system. However, it will only display the top 10 or show people and their respective scores.

**Comment by Kays** [comment]
It should also have a command like:
!points <user>

which gets the <user>'s points regardless if the user is in the top 10. I'm thinking of calling this a reputation (rep) system.

**Comment by Kays** [comment]
Ooops, wrong button

**Comment by myano** [comment]
lol, way to go! :P
