### ISSUE TITLE
Display a list of channels sophia is in

### ISSUE THREAD

**Issue by Kays** [Kays/sophia#51]
This is trivial. A command for admins/founders to see what channels sophia is in.

**Comment by Kays** [comment]
Hmm... I've sort of looked at this and I don't think there is a way to accurately report all channels sophia is in. We can keep a hash of channels sophia "joins" but we cannot accurately measure if sophia is really in that channel. For example, if sophia is banned, it'll show that sophia "joins" there because there's no way to verify it.

**Comment by myano** [comment]
What about making a command of "possible" channels sophia is in. It would be a start, no?

**Comment by Kays** [comment]
Yep, that's what I had in mind.
